# Generated by Django 3.2.12 on 2022-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20220311_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='stage_no',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
